### ISSUE TITLE
Wrong path for `routes` and `Redux DevTools`

### ISSUE THREAD

**Issue by maebe22** [srph/react-redux-starter-kit#16]
I have encountered a `Module not found` error when compiling the script. I Solved it when i change the path of routes from `./routes` to `../routes` and also in dev tools. May i know if this is an error or you purposely set the path like this.

**Comment by srph** [comment]
Are you using the code from the latest commit?

**Comment by maebe22** [comment]
i freshly clone earlier so probably i've used the latest commit

**Comment by srph** [comment]
Fixing this in a minute.

**Comment by srph** [comment]
Thanks!
