### ISSUE TITLE
Object spreading

### ISSUE THREAD

**Issue by maebe22** [srph/react-redux-starter-kit#20]
whenever i add this `...state` on my code like this,
```es6
case MY_ACTION:
  return {
    ...state,
    isFetching: false
  };
```
my console logs a `syntax error` pointing on the first dot of `...state`.

Is there something i forgot to do that's why i get this error?

PS: Sorry for bad explanation.

**Comment by srph** [comment]
Not sure how that's related to this repo.

Your example doesn't show any `console.log`. I suggest that you send a repo reproducing the problem. Fork, then send me the branch.
